project:
  type: website
  output-dir: docs

website:
  title: "Xiaoyi's blog"
  navbar:
    right:
      - about.qmd
      - icon: cv
      - icon: github
        href: https://github.com/xiaoyiliuXL
      - icon: twitter
        href: https://twitter.com/xiaoyiliu07
format:
  html:
    theme: cyborg
    css: styles.css

editor: visual

